/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialsRouteImport } from './routes/specials'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as MenuItemIdRouteImport } from './routes/menu.$itemId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SpecialsRoute = SpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const MenuItemIdRoute = MenuItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MenuRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/api/chat': typeof ApiChatRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/api/chat': typeof ApiChatRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/orders': typeof OrdersRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/api/chat': typeof ApiChatRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/specials'
    | '/api/chat'
    | '/menu/$itemId'
    | '/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/specials'
    | '/api/chat'
    | '/menu/$itemId'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/menu'
    | '/orders'
    | '/specials'
    | '/api/chat'
    | '/menu/$itemId'
    | '/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  MenuRoute: typeof MenuRouteWithChildren
  OrdersRoute: typeof OrdersRouteWithChildren
  SpecialsRoute: typeof SpecialsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specials': {
      id: '/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof SpecialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/menu/$itemId': {
      id: '/menu/$itemId'
      path: '/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof MenuItemIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteChildren {
  MenuItemIdRoute: typeof MenuItemIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuItemIdRoute: MenuItemIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  MenuRoute: MenuRouteWithChildren,
  OrdersRoute: OrdersRouteWithChildren,
  SpecialsRoute: SpecialsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
