/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialsRouteImport } from './routes/specials'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuItemIdRouteImport } from './routes/menu.$itemId'

const SpecialsRoute = SpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuItemIdRoute = MenuItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/menu/$itemId': typeof MenuItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/menu/$itemId': typeof MenuItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/menu': typeof MenuRouteWithChildren
  '/specials': typeof SpecialsRoute
  '/menu/$itemId': typeof MenuItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/menu' | '/specials' | '/menu/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/menu' | '/specials' | '/menu/$itemId'
  id: '__root__' | '/' | '/auth' | '/menu' | '/specials' | '/menu/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MenuRoute: typeof MenuRouteWithChildren
  SpecialsRoute: typeof SpecialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specials': {
      id: '/specials'
      path: '/specials'
      fullPath: '/specials'
      preLoaderRoute: typeof SpecialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$itemId': {
      id: '/menu/$itemId'
      path: '/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof MenuItemIdRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface MenuRouteChildren {
  MenuItemIdRoute: typeof MenuItemIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuItemIdRoute: MenuItemIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MenuRoute: MenuRouteWithChildren,
  SpecialsRoute: SpecialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
